# Generated by Django 4.1.4 on 2023-01-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newz", "0002_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="newssite",
            name="htmlClass",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="newssite",
            name="tag",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
