# Generated by Django 4.1.4 on 2023-01-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newz", "0003_newssite_htmlclass_newssite_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="newssite",
            name="hrefPrefix",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
