# Generated by Django 4.1.4 on 2023-01-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newz", "0005_alter_newssite_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="headline",
            name="news_site",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="newz.newssite",
            ),
            preserve_default=False,
        ),
    ]
