# Generated by Django 4.1.4 on 2023-01-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newz", "0006_headline_news_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="headline",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
